In [4]:
import numpy as np
import torch

# random variable, 5 rows, 1 lines (sampled from uniform distribution)
print(np.random.rand(5,1))
print(torch.rand(5,1))

# tensor, size=(5,2,3)

# what is tensor?
# An nth-rank tensor in m-dimensional space is a mathematical 
# object that has n indices and m^n components and obeys certain 
# transformation rules. Each index of a tensor ranges over the 
# number of dimensions of space.

print(np.random.rand(5,2,3))
print(torch.rand(5,2,3))

[[0.28870136]
 [0.9540892 ]
 [0.01625154]
 [0.24450752]
 [0.99798633]]
tensor([[0.1408],
        [0.4722],
        [0.9005],
        [0.3118],
        [0.0018]])
[[[0.64504874 0.12055321 0.12799734]
  [0.98072277 0.68286678 0.38098941]]

 [[0.60266069 0.8263908  0.8004847 ]
  [0.61803058 0.89462345 0.30737811]]

 [[0.53239556 0.97960348 0.97594345]
  [0.96280887 0.45594052 0.57929977]]

 [[0.14327942 0.2960228  0.03794772]
  [0.13646464 0.05326727 0.03354095]]

 [[0.0396288  0.61783765 0.13560632]
  [0.68368101 0.41679801 0.78873353]]]
tensor([[[0.6475, 0.7817, 0.2720],
         [0.8573, 0.8552, 0.5179]],

        [[0.8207, 0.8658, 0.5993],
         [0.6501, 0.9880, 0.2267]],

        [[0.5119, 0.9402, 0.1005],
         [0.6301, 0.7569, 0.8322]],

        [[0.3715, 0.9068, 0.9564],
         [0.0435, 0.4144, 0.5102]],

        [[0.4296, 0.6056, 0.9866],
         [0.6918, 0.3146, 0.8517]]])


In [21]:
# calucate y = 2 * x1 + x2^2 - x3 in numpy
x = np.ones((1,15))
print(x)
x1 = x[0,:5]
x2 = x[0,5:10]
x3 = x[0,10:15]
y = 2 * x1 + x2 ** 2 - x3
print(y)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[2. 2. 2. 2. 2.]


In [28]:
# calucate y = 5 * x1 + x2^2 - x3 in pytorch
x = torch.ones(1,15)
x.requires_grad = True
print(x)
x1 = x[0,:5]
x2 = x[0,5:10]
x3 = x[0,10:15]
y = 5 * x[0,:5] + x[0,5:10] ** 2 - x[0,10:15]
print(y)
s = torch.sum(y)
s.backward()
print(x.grad.data)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
       requires_grad=True)
tensor([5., 5., 5., 5., 5.], grad_fn=<SubBackward0>)
tensor([[ 5.,  5.,  5.,  5.,  5.,  2.,  2.,  2.,  2.,  2., -1., -1., -1., -1.,
         -1.]])
